### ISSUE TITLE
Using version strategy

### ISSUE THREAD

**Issue by keekkenen** [nebula-plugins/nebula-release-plugin#105]
Hi, I am cannot understand what for versionStrategy() method..
for, example, last git tag v.0.2.1, current branch named bugfix/super-bug
I call devSnapshot and was created artifact 
test-version-0.3.0-dev.61.uncommitted+super.bug.335ed0f.jar

After I added 
release {
	versionStrategy(DEVELOPMENT.copyWith(preReleaseStrategy: PreRelease.STAGE_FLOAT))
}
I think it will be changed version like exclude commit count and show uncommited, but it not that, why?
I have new artifact named like  test-version-0.2.1-dev+335ed0f.jar, why it's that and what' wrong ?

How can I change some correct project version, for example, add to version a feature (hotfix, bugfix) name ?

**Comment by keekkenen** [comment]
Ok, I am resolved it's questions

**Comment by mytechtoday** [comment]
@keekkenen  how did you end up fixing this issue ?

**Comment by keekkenen** [comment]
@mytechtoday Hi, I use DEVELOPMENT as a default version strategy and for it I made redefine normalStrategy option, It's look like Normal.useScope(ChangeScope.MINOR)
