### ISSUE TITLE
Candidate and uncommited changes

### ISSUE THREAD

**Issue by keekkenen** [nebula-plugins/nebula-release-plugin#108]
Hi, 
why candidate and final task does check changes in local git repo and doesn't do it for remote ?
It's look like strange situation - made few changes and local commit, and after call candidate (publish) task, but in remote git repo code is old?!

**Comment by rpalcolea** [comment]
I don't believe the purpose of the plugin is to pull something from the remote as we leave engineers to handle that by themselves instead of enforcing them to pull whatever from the remote

I don't think it is in our plans to modify this behavior
