### ISSUE TITLE
Commit error when executing "final" task

### ISSUE THREAD

**Issue by bootFyre17** [nebula-plugins/nebula-release-plugin#111]
I am trying to execute the "final" task provided by the plugin, but when I do I get the following error: org.gradle.api.GradleException: Final and candidate builds require all changes to be committed into Git.

The current git workspace is clean with no changes in the tree. 

I am using version 5.0.0 of the nebula plugin and do not know how to move forward.

**Comment by sghill** [comment]
@bootFyre17 can you paste the complete output with v6.3.5? Starting with [v6.0.1](https://github.com/nebula-plugins/nebula-release-plugin/releases/tag/v6.0.1) added, modified, and removed files were listed with the failure.

**Comment by bootFyre17** [comment]
it looks like my issue was caused by a poorly written gitignore file and some hidden updates that I wasn't seeing in my IDE and terminal. After a few hours of cleaning up I was able to get a candidate task to execute successfully. I think I'm all set now. I apologize for the issue and thank you for the response!
