### ISSUE TITLE
SNAPSHOT version remains in pom.xml when publish is run before release

### ISSUE THREAD

**Issue by abialas** [nebula-plugins/nebula-release-plugin#112]
I am using nebula-release-plugin in my CI/CD pipeline to publish artifacts to the Nexus. However, before I publish them I need to run tests on it (smoke automated tests etc.).
 
I have three different git repositories - let's take for example A, B, C. Repo B depends on repo A, repo C depends on repo A and B. To have local build on which I can run test I first execute maven publishing (gradlew publishToMavenLocalRepo) on repo A and B. On repo C I run gradlew build. 
It gives me an artifact I can test (the result of build repo C). 
When all tests pass I want to publish these artifacts (from each repo) so I run release develop snapshot from nebula. 
However, the version in pom.xml for the project C (the dependencies to A and B) remains with SNAPSHOT e.g. 1.0.0-SNAPSHOT instead of released version. 
Is it possible to update it after I run local publish?

**Comment by rpalcolea** [comment]
This isn't an issue with nebula-release itself

I believe this is more on your release process

you might want to do final releases on this case `./gradlew final` and then hook your publishing to nexus tasks to upload the JARs after a final tag was created. We do those things for bintray https://github.com/nebula-plugins/nebula-release-plugin/blob/661201b4923daafa9813fefc59dd32065cc4eb35/src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy#L272
