### ISSUE TITLE
Could not resolve all dependencies for ImmutableASTTransformation.checkImmutable

### ISSUE THREAD

**Issue by theburhan** [nebula-plugins/nebula-release-plugin#137]
While running the command on nebula release 9.2.0

I checked for release 9.0.0 the error does not exists, something went wrong in the later releases.

`
./gradlew clean build final -Prelease.scope=minor
`
I get the following err

```
* What went wrong:
Could not determine the dependencies of task ':library:compileJava'.
> Could not resolve all dependencies for configuration ':library:compileClasspath'.
   > No signature of method: static org.codehaus.groovy.transform.ImmutableASTTransformation.checkImmutable() is applicable for argument types: (java.lang.Class, java.lang.String, nebula.plugin.release.git.semver.ChangeScope, java.util.ArrayList, java.util.ArrayList) values: [class nebula.plugin.release.git.semver.SemVerStrategyState, ...]
     Possible solutions: checkImmutable(java.lang.Class, java.lang.String, java.lang.Object), checkImmutable(java.lang.String, java.lang.String, java.lang.Object)

```

**Comment by chali** [comment]
Hi @theburhan could you share a sample project where you see this error. It looks like there might be a conflict with other plugin dependencies.

**Comment by vmahuvak** [comment]
Hi, I am getting an error on Cloud Build when I compile my project
Here is the log

FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/devops-serimmune/r/mytest2
 * branch            162f098d5a23b94a60d2fbf9c14bf2da41d7ab99 -> FETCH_HEAD
HEAD is now at 162f098 removed dir argument
BUILD
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/gradle
Step #0: Download https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/2.0.4/com.github.johnrengelman.shadow.gradle.plugin-2.0.4.pom
Step #0: Download https://plugins.gradle.org/m2/nebula/release/nebula.release.gradle.plugin/11.1.0/nebula.release.gradle.plugin-11.1.0.pom
Step #0: Download https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/2.0.4/shadow-2.0.4.pom
Step #0: Download https://plugins.gradle.org/m2/com/netflix/nebula/nebula-release-plugin/11.1.0/nebula-release-plugin-11.1.0.pom
Step #0: Download https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.4.4/groovy-backports-compat23-2.4.4.pom
Step #0: Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/5.3.0.201903130848-r/org.eclipse.jgit-5.3.0.201903130848-r.pom
Step #0: Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit-parent/5.3.0.201903130848-r/org.eclipse.jgit-parent-5.3.0.201903130848-r.pom
Step #0: Download https://plugins.gradle.org/m2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.pom
Step #0: Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Step #0: Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.pom
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jsch/0.1.54/jsch-0.1.54.pom
Step #0: Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/6/oss-parent-6.pom
Step #0: Download https://plugins.gradle.org/m2/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.pom
Step #0: Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Step #0: Download https://plugins.gradle.org/m2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.pom
Step #0: Download https://plugins.gradle.org/m2/org/slf4j/slf4j-parent/1.7.2/slf4j-parent-1.7.2.pom
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpg-jdk15on/1.60/bcpg-jdk15on-1.60.pom
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.pom
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpkix-jdk15on/1.60/bcpkix-jdk15on-1.60.pom
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.pom
Step #0: Download https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/2.0.4/shadow-2.0.4.jar
Step #0: Download https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.4.4/groovy-backports-compat23-2.4.4.jar
Step #0: Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.jar
Step #0: Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/5.3.0.201903130848-r/org.eclipse.jgit-5.3.0.201903130848-r.jar
Step #0: Download https://plugins.gradle.org/m2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jsch/0.1.54/jsch-0.1.54.jar
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.jar
Step #0: Download https://plugins.gradle.org/m2/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.jar
Step #0: Download https://plugins.gradle.org/m2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpg-jdk15on/1.60/bcpg-jdk15on-1.60.jar
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpkix-jdk15on/1.60/bcpkix-jdk15on-1.60.jar
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.jar
Step #0: Download https://plugins.gradle.org/m2/com/netflix/nebula/nebula-release-plugin/11.1.0/nebula-release-plugin-11.1.0.jar
Step #0: 
Step #0: FAILURE: Build failed with an exception.
Step #0: 
Step #0: * Where:
Step #0: Build file '/workspace/build.gradle' line: 67
Step #0: 
Step #0: * What went wrong:
Step #0: A problem occurred evaluating root project 'workspace'.
Step #0: > No signature of method: static org.codehaus.groovy.transform.ImmutableASTTransformation.checkImmutable() is applicable for argument types: (java.lang.Class, java.lang.String, nebula.plugin.release.git.semver.ChangeScope, java.util.ArrayList, java.util.ArrayList) values: [class nebula.plugin.release.git.semver.SemVerStrategyState, ...]
Step #0:   Possible solutions: checkImmutable(java.lang.Class, java.lang.String, java.lang.Object), checkImmutable(java.lang.String, java.lang.String, java.lang.Object)
Step #0: 
Step #0: * Try:
Step #0: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Step #0: 
Step #0: * Get more help at https://help.gradle.org
Step #0: 
Step #0: BUILD FAILED in 41s
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/gradle" failed: exit status 1

All I do on build.gradle line 67 is version = version.split("-")[0] to remove every thing after version number starting from - e.g. Inferred project: mytest2, version: 1.0.3-dev.0+162f098
I only want 1.0.3 in version.
Any suggestions??
shadowJar {
  baseName = appName
  //add this line to get version using nebula.release
  version = version.split("-")[0]
  classifier = null
  manifest {
    attributes 'Main-Class': mainClass
  }
}

**Comment by vmahuvak** [comment]
I got similar problem today when I tried to build by jar using gradle and nebula release plugin 11.1.0 on CLoudBuild. Here is the exception
starting build "8756fc3f-1b2a-45ba-9926-b533e87774b4"

FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/devops-serimmune/r/mytest2
 * branch            162f098d5a23b94a60d2fbf9c14bf2da41d7ab99 -> FETCH_HEAD
HEAD is now at 162f098 removed dir argument
BUILD
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/gradle
Step #0: Download https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/2.0.4/com.github.johnrengelman.shadow.gradle.plugin-2.0.4.pom
Step #0: Download https://plugins.gradle.org/m2/nebula/release/nebula.release.gradle.plugin/11.1.0/nebula.release.gradle.plugin-11.1.0.pom
Step #0: Download https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/2.0.4/shadow-2.0.4.pom
Step #0: Download https://plugins.gradle.org/m2/com/netflix/nebula/nebula-release-plugin/11.1.0/nebula-release-plugin-11.1.0.pom
Step #0: Download https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.4.4/groovy-backports-compat23-2.4.4.pom
Step #0: Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/5.3.0.201903130848-r/org.eclipse.jgit-5.3.0.201903130848-r.pom
Step #0: Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit-parent/5.3.0.201903130848-r/org.eclipse.jgit-parent-5.3.0.201903130848-r.pom
Step #0: Download https://plugins.gradle.org/m2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.pom
Step #0: Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Step #0: Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.pom
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jsch/0.1.54/jsch-0.1.54.pom
Step #0: Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/6/oss-parent-6.pom
Step #0: Download https://plugins.gradle.org/m2/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.pom
Step #0: Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Step #0: Download https://plugins.gradle.org/m2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.pom
Step #0: Download https://plugins.gradle.org/m2/org/slf4j/slf4j-parent/1.7.2/slf4j-parent-1.7.2.pom
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpg-jdk15on/1.60/bcpg-jdk15on-1.60.pom
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.pom
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpkix-jdk15on/1.60/bcpkix-jdk15on-1.60.pom
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.pom
Step #0: Download https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/2.0.4/shadow-2.0.4.jar
Step #0: Download https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.4.4/groovy-backports-compat23-2.4.4.jar
Step #0: Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.jar
Step #0: Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/5.3.0.201903130848-r/org.eclipse.jgit-5.3.0.201903130848-r.jar
Step #0: Download https://plugins.gradle.org/m2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jsch/0.1.54/jsch-0.1.54.jar
Step #0: Download https://plugins.gradle.org/m2/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.jar
Step #0: Download https://plugins.gradle.org/m2/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.jar
Step #0: Download https://plugins.gradle.org/m2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpg-jdk15on/1.60/bcpg-jdk15on-1.60.jar
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcpkix-jdk15on/1.60/bcpkix-jdk15on-1.60.jar
Step #0: Download https://plugins.gradle.org/m2/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.jar
Step #0: Download https://plugins.gradle.org/m2/com/netflix/nebula/nebula-release-plugin/11.1.0/nebula-release-plugin-11.1.0.jar
Step #0: 
Step #0: FAILURE: Build failed with an exception.
Step #0: 
Step #0: * Where:
Step #0: Build file '/workspace/build.gradle' line: 67
Step #0: 
Step #0: * What went wrong:
Step #0: A problem occurred evaluating root project 'workspace'.
Step #0: > No signature of method: static org.codehaus.groovy.transform.ImmutableASTTransformation.checkImmutable() is applicable for argument types: (java.lang.Class, java.lang.String, nebula.plugin.release.git.semver.ChangeScope, java.util.ArrayList, java.util.ArrayList) values: [class nebula.plugin.release.git.semver.SemVerStrategyState, ...]
Step #0:   Possible solutions: checkImmutable(java.lang.Class, java.lang.String, java.lang.Object), checkImmutable(java.lang.String, java.lang.String, java.lang.Object)
Step #0: 
Step #0: * Try:
Step #0: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Step #0: 
Step #0: * Get more help at https://help.gradle.org
Step #0: 
Step #0: BUILD FAILED in 41s
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/gradle" failed: exit status 1

Any suggestion why it is giving this error on Cloudbuild but works locally on Mac and windows

**Comment by vmahuvak** [comment]
> Hi @theburhan could you share a sample project where you see this error. It looks like there might be a conflict with other plugin dependencies.

Hi Martin,

I am getting same error when I do a build on Google Cloud Build as Burharn is getting.

I am using version 11.1.0. Should I use version 9.0.0?
Please let me know.

**Comment by rpalcolea** [comment]
Hi folks, which version of gradle are you using

Gradle introduced new versions of groovy over the past few releases, specially on Gradle 5

On that time, Groovy had an issue with how they handled the ImmutableAstTransformation

This might be related to https://issues.apache.org/jira/browse/GROOVY-8806?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16636494 

I don't think there is a fix from nebula side as this might be specific to your environment

**Comment by vmahuvak** [comment]
Hi,

This error doesn't show up when I setup release.version in gradle.properties file. I got it all figured out with Google team and got it working.
