### ISSUE TITLE
[Question] Integration with tschulte/gradle-semantic-release-plugin

### ISSUE THREAD

**Issue by tinesoft** [nebula-plugins/nebula-release-plugin#157]
Hi Nebula team 👋 

Is there a way to integrate this awesome library with @tschulte's [gradle-semantic-release-plugin](https://github.com/tschulte/gradle-semantic-release-plugin)? which provides:
- fully automated version management and package publishing
- automatic generation of changelog based on commit messages,
- automatic support for most branching strategies (Git-Flow, Github-Flow, Master Only, etc)
- publication on github release
- etc

If that is so, could you document on how to achieve that?

Thanks you in advance

**Comment by chali** [comment]
Hi @tinesoft, unfortunately, we haven't attempted such integration. I was looking briefly what the plugin you mentioned offers and it seems there is some overlap in features so I think it is more question choosing one or the other than integrating them together. Feel free to share your progress if you have some conclusion on how they could work together.

**Comment by tinesoft** [comment]
Hi @chali,

After some quick investigation, i reached the same conclusion as you,
that the 2 plugins do overlap, even that they are not compatible( i.e both declare `release` task, which causes an error in the build). 


Thank you for taking the time anyway, appreciated!
