### ISSUE TITLE
unspecified version when publish to bintray

### ISSUE THREAD

**Issue by acidelk** [nebula-plugins/nebula-release-plugin#159]
When i try to publish to bintray with build.gradle
```
	id 'nebula.nebula-bintray-publishing' version '6.0.6'
	id 'nebula.release' version '11.1.0'
```
Then uploadToBintray task execute with `unspcified` version
```
Uploading to https://api.bintray.com/content/..../maven/error-handling/unspecified/com/....-sources.jar...
```
solution - flip applying order:
```
	id 'nebula.release' version '11.1.0'
	id 'nebula.nebula-bintray-publishing' version '6.0.6'
```
and version is specified
```
Uploading to https://api.bintray.com/content/..../maven/error-handling/0.0.1/com/....-sources.jar...
```

**Comment by rpalcolea** [comment]
Hi @acidelk , thanks for reporting this issue.

I found that historically we just checked for the presence of a given class, so it was expected that bintray or build-info-extractor plugins were applied after release plugin. 

I just changed this approach to configure the tasks when the plugin  applied as in https://github.com/nebula-plugins/nebula-release-plugin/pull/161/files#diff-5e0f6551dac63067eb765284766c5704R273

Let me know if this works for you

**Comment by acidelk** [comment]
Many thx. But I can't test now. :)
