### ISSUE TITLE
Tag support for v2020-05-07-1 format

### ISSUE THREAD

**Issue by kzhu2012** [nebula-plugins/nebula-release-plugin#186]
Currently we are trying to adopt the **v2020-05-07-1** format (last digit stands for build number for the build day)for tag, and by reading through the documentation and trying, looks like it's not supportable:

1.  v2020.5.7 is workable, but it strips out all the leading zero.  Behind the scene, everything is still treated as a number.
2. v2020.5.7-rc.1 is kind of a work-around, but not quite what we want, and it only works with candidate task, not final task.

Is it configurable to add the tag format of **v2020-05-07-1**?  If yes, will it be treated as valid date (year, month, day), or still just number?

Thanks

**Comment by DanielThomas** [comment]
The plugin supports semver and is about managing release lines and release promotion, which isn't what you'd be doing with that kind of scheme. If you want `<timestamp>.<build>` that feels something suited for continuous releases - use your own logic to set the version and always publish, and treat every build as a release candidate.
