### ISSUE TITLE
Update jgit and grgit versions

### ISSUE THREAD

**Issue by sdavids13** [nebula-plugins/nebula-release-plugin#189]
Our team would like to leverage the latest version of the [Spotless plugin](https://github.com/diffplug/spotless) but that version has a newer version of jgit than what the `nebula-reslease-plugin` currently provides. This results in an error seen here: https://github.com/ajoberstar/grgit/issues/309. Please update to jgit `5.7.0.202003110725-r` and grgit `4.0.2`

**Comment by rpalcolea** [comment]
Hi, thanks for reporting this

15.0.2 has these changes
