### ISSUE TITLE
better handling of project bootstrap errors

### ISSUE THREAD

**Issue by cfieber** [nebula-plugins/nebula-release-plugin#19]
Not sure if this is covered in #15 - and maybe it doesn't totally make sense in the context of this plugin itself but it does in the context of something like nebula.netflixoss bringing this in.

If you are just trying to set up a brand new project (and haven't even git init'd it yet) the error displayed is something along the lines of 'Unable to locate repository' which given the overloaded usage of the word repository in both gradle and git land can be confusing.  --stacktrace at least shows it coming from a git class which twigged that I should git init the thing (and then get an initial commit in place so it has a HEAD to locate)

**Comment by rspieldenner** [comment]
Yeah kind of a combination of having better error messages and just some more in the README.md to discuss the expectations. Like to build with the plugin you have to clone the git repo instead of just downloading a zip from github. etc.
