### ISSUE TITLE
nebula-release-plugin version is compatible with Gradle 6.3

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [nebula-plugins/nebula-release-plugin#191]
which nebula-release-plugin version is compatible with Gradle 6.3 ?
Can you please provide the compatibility matrix

**Comment by chali** [comment]
Duplicate question. See https://github.com/nebula-plugins/nebula-publishing-plugin/issues/169

**Comment by wlsc** [comment]
It is not a duplicate question as release notes (here on GitHub) for release plugin do not have such information.
