### ISSUE TITLE
candidate task failing with Invalid branch name

### ISSUE THREAD

**Issue by hsharma86** [nebula-plugins/nebula-release-plugin#195]
Hi,
I created two different branches with name "release" and "release-1.0.0", but when i ran candidate task it failed for both of them sayind branch name does not match allowed patterns.

**Comment by DanielThomas** [comment]
The default release branch patterns are `release/<version>` or `release-<version>`:

https://github.com/nebula-plugins/nebula-release-plugin#extension-provided

**Comment by hsharma86** [comment]
Hi @DanielThomas

Thanks for your reply.
I used the default branch pattern 'release-<version>', but it still failed with below error:

> Task :releaseCheck FAILED
Branch **release-1.0.0** does not match one of the included patterns: [master, HEAD, (release(-|/))?\d+(\.\d+)?\.x, v?\d+\.\d+\.\d+]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':releaseCheck'.
> Branch **release-1.0.0** does not match one of the included patterns: [master, HEAD, (release(-|/))?\d+(\.\d+)?\.x, v?\d+\.\d+\.\d+]

**Comment by chali** [comment]
@hsharma86 the branch name is not matching the regex. You need to end with `x` so branch `release-1.0.x` should do the job. The idea is that you will continue releasing patches within the branch.
