### ISSUE TITLE
release.version can be set to empty string/null but is still used

### ISSUE THREAD

**Issue by plumlee** [nebula-plugins/nebula-release-plugin#20]
Noticed while playing with various options in a Jenkins build that I can pass `-Prelease.version= -Prelease.scope=patch`  and that created a tag of `v`. That is, a blank value for the version is accepted. This is on 2.2.4. 

Seems like the point of the plugin would be to enforce server, so a version specified that doesn’t validate as server ought to be rejected or ignored. 

In my case, I was hoping that I could pass a blank there and have that property ignored, which would be ideal for my use case but perhaps not what you’d prefer.

**Comment by rspieldenner** [comment]
-Prelease.version as written now is an override. So if it is in place what
ever it is set to will win. I can see enforcing it as semver, and shall add
an issue to that effect. Hopefully I can get to it in the next week or two.

We do accept pull requests if you can get to it before I do.

**Comment by plumlee** [comment]
I’d do the PR myself, but I’m not a Java dev, so it’s a strange new world for me.  :)  I think it might be enough to just ignore the flag entirely if an empty value is passed, although that might cause issues as well. Perhaps erring out or requiring a server value is best to the behavior is explicit.

Appreciate all your work here - it’s a nice tool

**Comment by rspieldenner** [comment]
Fixed
