### ISSUE TITLE
immutableSnapshot (TimestampUtil) creates wrong timestamp when last days of december is in week 1

### ISSUE THREAD

**Issue by asoee** [nebula-plugins/nebula-release-plugin#206]
TimestampUtil uses the pattern "YYYYMMddHHmm", which uses the week based year.
When the 29th of december is in week 1, it will then use the year of that week.
So: 2020-12-29 becomes 2021-12-29
I believe the solution is to use "yyyyMMddHHmm" instead.

**Comment by rpalcolea** [comment]
Hello @asoee , 

You are right, `YYYY` takes the week based year. thanks for bringing this up!

We just released https://github.com/nebula-plugins/nebula-release-plugin/releases/tag/v15.3.1 with the fix
