### ISSUE TITLE
Question - possible to change scope for a devSnapshot build based on branch ancestry?

### ISSUE THREAD

**Issue by plumlee** [nebula-plugins/nebula-release-plugin#21]
Not even sure if this makes sense, but we do release branches, and sometimes feature branches off those. However, if we do a final release of `v1.1.0` on `release/1.1.x`, then the next inferred version by the `devSnapshot` task for our feature builds thinks we should jump to `v1.2.0`. I want this behavior if I’m on master, but not when I am on a long lived release branch.

I’m thinking an implementation that reads release branch structure and does the following:
- if on a branch like `release/1.1.x`, run devSnapshot tasks with scope=patch
- if on a branch like `release/1.x.x, run devSnapshot tasks with scope=minor

Do you think this would even be possible?

**Comment by rspieldenner** [comment]
Yeah, I've noticed the problem on release/1.1.x. I need to find a way to
make the gradle-git plugin I'm building on to make my default of
scope=minor to not always apply.

**Comment by rspieldenner** [comment]
This is fixed in gradle-git 1.3.0 which will be used by nebula-release 3.0.0 (which will be released today or tomorrow)
