### ISSUE TITLE
Only tags are pushed to the origin

### ISSUE THREAD

**Issue by ckazimie** [nebula-plugins/nebula-release-plugin#212]
Hi 

I recently upgraded from version 13.0.0 to 15.3.1 and noticed only tags are pushed to the origin, not the commits.
Is this an error or there is a configuration to push all commits as well?

I mean the final task.

**Comment by chali** [comment]
Hi @ckazimie this is an expected change introduced by `14.0.0`. https://github.com/nebula-plugins/nebula-release-plugin/releases/tag/v14.0.0
