### ISSUE TITLE
Release branch with .x

### ISSUE THREAD

**Issue by stewartbryson** [nebula-plugins/nebula-release-plugin#24]
Could you explain to me the choice to make the default release branch name regexp end with an explicit ".x"? I understand that I am able to change this (thanks very much for that), but I was hoping to understand the thinking here a little bit better. All the Gitflow articles I have read, including Driessen's, use release branches with names like 'release-2.2'.

Thank you.

**Comment by rspieldenner** [comment]
Many of Netflix's OSS projects use branches like 2.x or 3.x for maintaining separate branches so that's the default I chose. No strong opinion on that point.

**Comment by stewartbryson** [comment]
Thanks.
