### ISSUE TITLE
Skip Git Configuration Check for If None of the Plugin's Tasks Will Run

### ISSUE THREAD

**Issue by EarthCitizen** [nebula-plugins/nebula-release-plugin#256]
Our pipeline has a security job that runs which we do not control. It is there by security compliance, and runs against the project in its own Docker container that we cannot add any scripts to, and it executes Gradle on its own to do the scanning. Therefore, we cannot set up the Git username and so forth before it executes. And since the release plugin checks for this when applied, this security scan job fails due to the release plugin failing because of no Git username.

Since the Git information is not actually needed unless the release plugin's tasks are run, it seems the check for this information should be only be done when the tasks are actually going to execute.

**Comment by rpalcolea** [comment]
Hi @EarthCitizen , thanks for bringing this up

We added this in 19.0.5. Can you give it a try and let us know if this fulfill your needs?

Thanks

**Comment by EarthCitizen** [comment]
@rpalcolea I will try it and let you know

**Comment by EarthCitizen** [comment]
@rpalcolea Apologies for the late reply. `19.0.5` does indeed fix the issue.
