### ISSUE TITLE
Plugin can not be applied if root project does not have release task

### ISSUE THREAD

**Issue by artem-zinnatullin** [nebula-plugins/nebula-release-plugin#33]
Steps to reproduce:

1. Clone RxJava repo https://github.com/ReactiveX/RxJava
2. Create subdir `rxjava`
3. Move `src`, `build.gradle`, `gradle.properties` to the `rxjava` folder
4. Change `settings.gradle` to `include ':rxjava'`

The problem is that this plugin thinks that `rootProject` declares `release` task, but this is not true for setup when root project is just a container for subprojects (which is normal and common setup).

`project.rootProject.tasks.release.dependsOn(task)` in the `ReleasePlugin` — is the reason of failure with message: Could not find property 'release' on task set.

**Comment by rspieldenner** [comment]
No plans to change this behavior. Designed to release entire directory
together, so root should apply the plugin.

**Comment by artem-zinnatullin** [comment]
But why? :( Do you see some drawbacks of subproject structure? I'm blocked by this in https://github.com/ReactiveX/RxJava/issues/3503.

**Comment by rspieldenner** [comment]
I think projects with different release cadences should be in different
repositories.

**Comment by rspieldenner** [comment]
So

    // build.gradle at root of project
    allprojects {
      apply plugin: 'nebula.nebula-release'
    }

    // build.gradle in rxjava subdir
    // whatever plugins and dependencies as needed

**Comment by artem-zinnatullin** [comment]
@rspieldenner applying plugin to `allprojects` works, thanks!
