### ISSUE TITLE
artifactorypublish execute when run final task

### ISSUE THREAD

**Issue by GrapeBaBa** [nebula-plugins/nebula-release-plugin#50]
Hi
 I am newbie to use nebula plugins,  i came across a issue when combine bintray and release plugin. When I execute final task, why artifactory still running and try to publish a non snapshot version to oss.jfrog.org. Another similar issue when  i execute snapshot task, why bintrayupload task also execute?

**Comment by DanielThomas** [comment]
Sounds like you need something like this - https://github.com/nebula-plugins/nebula-plugin-plugin/blob/master/src/main/groovy/nebula/plugin/plugin/NebulaPluginPlugin.groovy#L97-104

That's how we handle our OSS snapshot/release process.

**Comment by GrapeBaBa** [comment]
thanks @DanielThomas that is exactly what I want.
