### ISSUE TITLE
How to re-release existing tag

### ISSUE THREAD

**Issue by ajeets1978** [nebula-plugins/nebula-release-plugin#52]
How to re-release an already released or tag, when i have done further taggings and releases.

For example:

Two months back i released with rpm builds and with some tag 1.0.0, now i had already moved on to 2.0.0, but somehow i am realizing that i am missing some artefacts from the previous release and need to build the same release again. 

How can i do that, cos i can't use the last tag true which will be 2.0.0 and above, I can't use the release.version=1.0.0 cos that will reset the tagging i believe in the repository or complain or can mess with something else which i don't even want to try before, knowing if that will be the best way to re-release using nebula ?

**Comment by rspieldenner** [comment]
if you don't release to mavenCentral, delete old tag recreate tag.
Otherwise just put out a v2.0.1

**Comment by ajeets1978** [comment]
Thanks for the suggestion,but nope that is not what i am looking forward for, there should be a way to release the same artifcats. Maven has that capability. i don't want to tag 1.0.0 to 1.0.1 cos i am not changing anything in that, thats patching if you do any change is valid but not. What I am looking forward for.

**Comment by rspieldenner** [comment]
Other possibility is checkout to a point around the tag use `./gradlew final|candidate -Prelease.useLastTag=true

and we would welcome a pull request if none of those do what you want

**Comment by ajeets1978** [comment]
@rspieldenner no mate that doesn't hold true. As i said i further moved to the next tags, using useLastTag=true means that last one not something from in between.

I hope we need to understand what i was asking. Nebula Should not put that kind of restriction, building the same released tag again.

I released xyz-2.0.0.exe a long time but somehow i am not able to get that version / actual .exe. So i should be able to pull that tag and prepare the build with that tag only. I can do that very easily if i disable the nebula plugins. So instead of that nebula should have option to do that, anyways thanks so much. I will check with pull request as rspieldenner.

**Comment by rspieldenner** [comment]
So you should be able to `git checkout v2.0.0` then run `./gradlew final
-Prelease.useLastTag=true` and re-release v2.0.0
