### ISSUE TITLE
Gradle task to retrieve the generated version use nebula 

### ISSUE THREAD

**Issue by yarinkos** [nebula-plugins/nebula-release-plugin#53]
Hi,
after the build task,which produced new build version of our code,we want to call to a post gradle task.that will store/print/do somthing with the version that currently built 

Any suggest how to that that?

note: our project produce a zip with pom file and we upload it to nexus,
maybe we can retrieve to version from that pom using gradle task?
Thanks !

**Comment by rspieldenner** [comment]
You should have the task.outputs of whatever creates your archive to grab the file without needing to know the name or version. `project.version.toString()` should also have the version string
