### ISSUE TITLE
All changes commited error.

### ISSUE THREAD

**Issue by dvbeato** [nebula-plugins/nebula-release-plugin#55]
I'm trying to release a final version for my project, but the plugin keep validating, telling that a final release require all changes to be committed into Git. But I don't have changes to commit.
![screen shot 2016-06-19 at 8 30 11 am](https://cloud.githubusercontent.com/assets/213964/16177059/80871d6a-35f8-11e6-8101-c8b21471cda9.png)

**Comment by DanielThomas** [comment]
I've got a build here exhibiting the same problem. Going to look into that.

**Comment by mprivat** [comment]
Ever got this resolved? I have the exact same problem.

**Comment by mprivat** [comment]
Turns out to be related to git submodules in my case. Even though the submodule has no change in it, grgit sees a modification. I'm going remove submodules and deal with them another way.

**Comment by sghill** [comment]
This submodule issue was resolved with a JGit upgrade in [v6.0.0](https://github.com/nebula-plugins/nebula-release-plugin/releases/tag/v6.0.0).

In the event it was not the submodule bug, using [v6.0.1](https://github.com/nebula-plugins/nebula-release-plugin/releases/tag/v6.0.1) or later will now output the files that JGit thinks have changed.
