### ISSUE TITLE
Release patches with patch version from existing tag

### ISSUE THREAD

**Issue by ajeets1978** [nebula-plugins/nebula-release-plugin#56]
Releasing a patch should allow update of patch version, even if it is lower than the current master branch versions. This i believe is a critical issue. 

Think of same product running some different versions on different sites 4.2.0 and 4.3.0. Now you end up finding some bug in 4.2.0 you need to patch it with different branch and need to release 4.2.1 with scope patch creating a branch called 4.2.X, this is not allowed due to some strategy in the nebula release.

Example:

gradle final -x test -x integrationTest -Prelease.scope=patch
Inferred project: test-project, version: 4.11.1

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating script.
> Inferred version (4.11.1) cannot be lower than nearest (4.12.0-rc.7). Required by selected strategy.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by DanielThomas** [comment]
Semantically, that wouldn't be a patch release. The workflow is: if you don't already have a release branch for `v4.11.0`, branch at that tag, and land changes and release from there.

**Comment by ajeets1978** [comment]
Wish you could have understand my question? I need a process for patch release with nebula plugin which is not possible :(

**Comment by DanielThomas** [comment]
Patch releases are possible, but must follow the version strategy. In this case, you already have release candidates tagged and reachable on that branch. You need a release branch that branches from the v4.11.0 tag so you can make be release. 

If that's not what's going on, we'd need more information, as what you've provided above indicates this is the problem.

**Comment by rspieldenner** [comment]
a - b(v4.2.0) - c - d (v4.3.0) - g
       \_ e (on branch 4.2.x) - f 

i can release g as a patch and get v4.3.1, g as a minor and get v4.4.0, and f as a minor for v4.2.1

as long as d and g are not on the 4.2.x branch it will not see the v4.3.0 tag, and be able to release v4.2.1, v4.2.2 etc.

**Comment by ajeets1978** [comment]
No problem, I will put more information. Can i be the contributor as well ?
