### ISSUE TITLE
Can I have 2 releases branches with 2 different versions ? 

### ISSUE THREAD

**Issue by miclefebvre** [nebula-plugins/nebula-release-plugin#62]
Can I have a release/0.1.x and a release/0.2.x branches and do release in those 2 branches ? Example I want to do a fix in version 0.1.0 even if the version 0.2.2 exists.

I would like to be able to do gradle final in the release/0.1.x and it creates a 0.1.1 version. Is it doable ? I thought it would be possible but I don't know how.

**Comment by DanielThomas** [comment]
Yes it is - and that's exactly how it works. Make sure you branch `release/0.1.x` and `release/0.2.x` at the release tags for those minor releases so that later tags aren't reachable. Patch is the default release level, so you can simply use the standard tasks to release.

**Comment by miclefebvre** [comment]
Thank you.

I found didn't work.

I made several release to test on the same commit. So when I branched, my
branch had more than one version tag in it at the same commit.

Now it works.
