### ISSUE TITLE
Option not to push tags to a git repo on a release

### ISSUE THREAD

**Issue by jtk54** [nebula-plugins/nebula-release-plugin#68]
Howdy,

[Spinnaker](https://github.com/spinnaker/spinnaker) uses this extension to do its builds and releases. We are managing two different tag patterns for releases -- one with a build number and one without. We'd like to forego pushing the tags in certain types of releases while still specifying a version using `-Prelease.version=`, e.g.

```shell
./gradlew -Prelease.version=<someversion> -Prelease.noTagSync
```

where the version is overridden, but the tags aren't synced with the github repo.

Would you guys be open to a PR adding a flag to forego syncing tags? This seems like a reasonable thing to support, and shouldn't break any previous workflows.

**Comment by DanielThomas** [comment]
You'd want to handle that with a release strategy and dedicated task for that type of release:

- `org.ajoberstar.gradle.git.release.semver.SemVerStrategy` and in turn `ajoberstar.gradle.git.release.base.ReleaseVersion` carries a `createTag` field
- `nebula.plugin.release.NetflixOssStrategies` is where we define our version strategies
- `nebula.plugin.release.ReleasePlugin#apply` is where we configure the strategies, in this case you'd be adding a strategy w/ build number that doesn't create a tag
- Similarly you'd create a task for that particular phase that selects that strategy

That's something you can do without modifying the plugin, you could compose our plugin with the Spinnaker project plugin to provide the additional opinions you need. Maybe it has general utility, and we should add it to our default strategy - Can you expand on the use case? 

- What's the rationale for not wanting to push tags?
- What's the semantic difference between the versions?

**Comment by jtk54** [comment]
I think we managed to accomplish our task using `-Prelease.useLastTag`, so I'm closing this. Our actual issue was in the naming of the actual debian packages, which collided for multiple builds of the same semver (which we do while testing).

Just for posterity though, I'll answer the use case questions:

> What's the rationale for not wanting to push tags?

We want to run integration tests before our packages hit a public bintray repo, but we want to use gradle to build the packages from source for testing and publish to a private bintray repo before we deploy. We want to push the tags after validation only. `-Prelease.useLastTag` actually solves this issue for us.

> What's the semantic difference between the versions?

One set of versions is bumped and built once per release, with fixes and new features just resulting in new versions. One set of versions will build several times for a given semver release, and the build that finally passes vetting will be promoted.

**Comment by DanielThomas** [comment]
We have an alternate repository supported by the plugin - internal teams publish their external stuff as release candidates:

https://github.com/nebula-plugins/gradle-netflixoss-project-plugin#build-property-to-use-alternative-publishing-repository

So you could also test with candidates this way if you choose.
