### ISSUE TITLE
Not inferring correct version

### ISSUE THREAD

**Issue by Miniwa** [nebula-plugins/nebula-release-plugin#73]
I downloaded the plugin and and made a simple test project to play with.
After committing all changes and running the "final" command, the version was correctly set as "0.1.0"
However, I then immideiatly ran a build, and the project version was inferred as "0.2.0-dev.0+4a7632c", which is incorrect since there are no uncommited changes and 4a7632c is the "0.1.0" commit.
I've attached command output below, but I'm not sure how useful it is.

PS F:\Projects\<removed> ./gradlew final
:releaseCheck
:final
:prepare
:release
Inferred project: <removed>, version: 0.1.0
Tagging repository as v0.1.0
Pushing changes in [refs/heads/master, v0.1.0] to origin

PS F:\Projects\<removed> ./gradlew build
<build output>
Inferred project: <removed>, version: 0.2.0-dev.0+4a7632c
<build output>

**Comment by rspieldenner** [comment]
That is how it would work you've released 0.1.0 and working on 0.2.0 dev.0
means 0 commits since last tag

**Comment by Miniwa** [comment]
But there are no changes at all since the 0.1.0 version, is this really the intended behavior?
What if i need to rebuild the 0.1.0 version for whatever reason?

**Comment by rspieldenner** [comment]
if you really intend to rebuild 0.1.0 there is a useLastTag option. Expected use is moving forward so you wouldn't want a repeated candidate or release version.

**Comment by Miniwa** [comment]
Alright, thanks.
