### ISSUE TITLE
Improve Error Message When Version Already Set

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/nebula-release-plugin#79]
If the version property has already been set, the release task fails with this message:

```
* What went wrong:
Execution failed for task ':release'.
> No such property: inferredVersion for class: java.lang.String
```

**Comment by VITOLDO** [comment]
I have temporary fix for that but I don't think it's ok:
`version.inferredVersion = new ReleaseVersion(explicitVerison, previousVersion, shouldTagBeCreated)`
