### ISSUE TITLE
Question: Behavior across branches

### ISSUE THREAD

**Issue by kasperfrederiksen** [nebula-plugins/nebula-release-plugin#80]
We are using the release plugin and are a bit unsure of the correct behavior when working with multible branches.

The scenario:

1. We have a MASTER branch with tag v1.0.0. 
2. We branch out to a DEVELOP branch. This will get v1.0.1-SNAPSHOT when building.
3. We then commit changes to MASTER and release which will create tag v1.0.1
4. We see that if we build on DEVELOP branch - it will remain a 1.0.1-SNAPSHOT, but we would expect it to be v1.0.2-SNAPSHOT?

What is the expected behavior when we are working on multible branches?

Thanks!

**Comment by rspieldenner** [comment]
The plugin crawls back through commits to find the last tag to figure out
what the next version should be. So if you release a hotfix on master that
should get merged back to DEVELOP, then it would see the v1.0.1 tag and
start doing 1.0.2-dev.# or 1.1.0-dev.#

**Comment by kasperfrederiksen** [comment]
@rspieldenner Thanks for the quick reply and explanation.
