### ISSUE TITLE
RFE: allow adding additional `metadata` to the semantic version

### ISSUE THREAD

**Issue by noel-yap** [nebula-plugins/nebula-release-plugin#86]
Perhaps via `-Prelease.version.metadata=foo` or through a Gradle extension:

```
nebulaRelease {
  version.metadata = 'bar'
}
```

**Comment by rpalcolea** [comment]
We have discussed this in the past where folks would like to have "feature information" in the build metadata portion of the version.

While this is attractive to multiple folks, we don't believe it is the right answer for doing feature metadata as at the end, if you have tooling around semver, that information becomes irrelevant.

Gradle recommends using features where you can ship your artifact gradle metadata with the feature information and then consumers use it. 

Closing this as we are not planning to support custom version metadata in the plugin and we would like to only maintain the current workflow
