### ISSUE TITLE
Github not showing latest releases

### ISSUE THREAD

**Issue by vojbarzz** [nebula-plugins/nebula-release-plugin#98]
Hello, how to mark latest release made by `final` task as latest release on github automatically ? I would like to have working [/releaes/latest](https://github.com/nebula-plugins/nebula-release-plugin/releases/latest) functionality.

I use enterprise github, not public one.

**Comment by rpalcolea** [comment]
Hi,

I don’t think there’s something specific in the plugin that would do that

As long as you tag either manually or using the plugin, GitHub should detect the latest pushed tag.
